<a href="https://colab.research.google.com/github/Fahad-Alkhalidy/pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
print(torch.__version__)

2.2.1+cu121


In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.tensor([[7,8], [3,3]])
MATRIX

tensor([[7, 8],
        [3, 3]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1,2,3], [23,32,3],[2,3,5]]])
TENSOR

tensor([[[ 1,  2,  3],
         [23, 32,  3],
         [ 2,  3,  5]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR.ndim

3

###Random Tensors

In [19]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6239, 0.6123, 0.1430, 0.4648],
        [0.0775, 0.5297, 0.6598, 0.4664],
        [0.6971, 0.2016, 0.8560, 0.7755]])

In [20]:
random_tensor.ndim

2

In [21]:
random_image_size_tensor = torch.rand(23,212,23)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([23, 212, 23]), 3)

In [22]:
random_image_size_tensor

tensor([[[0.1891, 0.1235, 0.7745,  ..., 0.8688, 0.9367, 0.1922],
         [0.4888, 0.6768, 0.3584,  ..., 0.4728, 0.4463, 0.4747],
         [0.1461, 0.8072, 0.4564,  ..., 0.4256, 0.5647, 0.7536],
         ...,
         [0.4814, 0.8350, 0.1896,  ..., 0.6608, 0.8270, 0.1181],
         [0.4125, 0.0268, 0.4838,  ..., 0.8147, 0.8243, 0.7358],
         [0.6497, 0.5335, 0.3846,  ..., 0.5753, 0.8837, 0.6911]],

        [[0.5047, 0.6361, 0.6694,  ..., 0.6419, 0.8724, 0.0593],
         [0.0165, 0.9906, 0.5738,  ..., 0.4252, 0.5498, 0.0384],
         [0.1269, 0.7659, 0.4937,  ..., 0.8335, 0.0928, 0.0327],
         ...,
         [0.3136, 0.3834, 0.1298,  ..., 0.5304, 0.2025, 0.6486],
         [0.2365, 0.9309, 0.3140,  ..., 0.2514, 0.1178, 0.9692],
         [0.5197, 0.5233, 0.3556,  ..., 0.4573, 0.8702, 0.6964]],

        [[0.4124, 0.7581, 0.2458,  ..., 0.7937, 0.1983, 0.4762],
         [0.7479, 0.2281, 0.1884,  ..., 0.4128, 0.8178, 0.7871],
         [0.3297, 0.5600, 0.0875,  ..., 0.1384, 0.9222, 0.

##Zeros and ones

In [23]:
zeros = torch.zeros(2,3)

In [24]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
ones = torch.ones(2,3)

In [26]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

##creating a range of tensors and tensors-like

In [7]:
one_to_ten = torch.arange(start = 1, end=12, step =2)
one_to_ten

tensor([ 1,  3,  5,  7,  9, 11])

In [8]:
#creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)

In [9]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0])